name: 'Upload Package to Thunderstore'
description: 'Validates, packages and publishes a Thunderstore package'
author: 'WarperSan'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  # Required inputs
  community:
    description: 'Slug of the community to publish the package to'
    required: true
  team:
    description: 'Name of the team publishing the package'
    required: true
  name:
    description: 'Name of the package'
    required: true
  version:
    description: 'Semantic version of the package'
    required: true
  files:
    description: 'List of files to include in the package. Supports path mapping using "source -> destination"'
    required: true

  # Optional inputs
  categories:
    description: 'Slug of each category the package belongs to'
    required: false
    default: ''
  description:
    description: 'Short description of the package'
    required: false
    default: ''
  dependencies:
    description: 'Dependency strings for required packages'
    required: false
    default: ''
  website:
    description: "URL of the package's website"
    required: false
    default: ''
  has-nsfw:
    description: 'Marks the package as containing NSFW content'
    required: false
    default: 'false'

  # Secrets
  token:
    description: 'Authentication token used by the service account'
    required: true

  # Options
  host:
    description: 'URL of the Thunderstore server to publish to'
    required: false
    default: 'https://thunderstore.io'
  package-files:
    description: 'List of files to include on the package listing page'
    required: false
    default: |
      ./icon.png
      ./README.md
      ./CHANGELOG.md
      ./LICENSE?(.txt|.md)


runs:
  using: 'composite'
  steps:
    - name: Install ThunderPipe
      shell: bash
      run: |
        dotnet tool install ThunderPipe --global --version "$VERSION"
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      env:
        VERSION: '1.0.2'

    ### ---
    ### Validate Inputs
    ### ---
    - name: Validate Community
      shell: bash
      run: |
        ThunderPipe validate community "$COMMUNITY" \
          --host "$HOST"
      env:
        COMMUNITY: ${{ inputs.community }}
        HOST: ${{ inputs.host }}

    - name: Validate Categories
      shell: bash
      run: |
        [[ -z "$CATEGORIES" ]] && exit 0

        readarray -t categories <<< "$CATEGORIES"

        ThunderPipe validate categories "$COMMUNITY" "${categories[@]}" \
          --host "$HOST"
      env:
        COMMUNITY: ${{ inputs.community }}
        CATEGORIES: ${{ inputs.categories }}
        HOST: ${{ inputs.host }}

    - name: Validate Dependencies
      shell: bash
      run: |
        [[ -z "$DEPENDENCIES" ]] && exit 0

        readarray -t dependencies <<< "$DEPENDENCIES"
        
        ThunderPipe validate dependencies "${dependencies[@]}" \
          --host "$HOST"
      env:
        DEPENDENCIES: ${{ inputs.dependencies }}
        HOST: ${{ inputs.host }}

    ### ---
    ### Prepare Package
    ### ---
    - name: Copy Package Files
      shell: bash
      run: |
        rm -rf "$DESTINATION"
        mkdir -p "$DESTINATION"
        
        shopt -s nullglob
        mapfile -t patterns <<< "$FILES"
  
        for pattern in "${patterns[@]}"; do
          [[ -z "$pattern" ]] && continue
        
          for file in $pattern; do
            [[ -f "$file" ]] && cp "$file" "$DESTINATION"
          done
        done
      env:
        FILES: ${{ inputs.package-files }}
        DESTINATION: '${{ github.workspace }}/package/'

    - name: Copy Build Files
      shell: bash
      run: |
        shopt -s nullglob
        mapfile -t patterns <<< "$FILES"

        for pattern in "${patterns[@]}"; do
          [[ -z "$pattern" ]] && continue

          source="$pattern"
          dest="$DESTINATION"

          # Handle different outputs (A -> B)
          if [[ "$pattern" == *" -> "* ]]; then
            source="${pattern% -> *}"
            dest="$DESTINATION/${pattern#* -> }"
          fi

          # Copy files
          mkdir -p "$dest"
          IFS=$'\n'
          for file in $source; do
            [[ -f "$file" ]] || continue
            echo "Copying '$file' to '$dest'"
            cp "$file" "$dest"
          done
          unset IFS
        done
      env:
        FILES: ${{ inputs.files }}
        DESTINATION: '${{ github.workspace }}/package/plugins/'

    - name: Create manifest.json
      shell: bash
      run: |
        OPTIONS=()
        
        if [ -n "$DIRECTORY" ]; then
          OPTIONS+=('--output-dir')
          OPTIONS+=("$DIRECTORY")
        fi

        if [ -n "$DESCRIPTION" ]; then
          OPTIONS+=('--description')
          OPTIONS+=("$DESCRIPTION")
        fi
        
        if [ -n "$WEBSITE" ]; then
          OPTIONS+=('--website')
          OPTIONS+=("$WEBSITE")
        fi
        
        if [ -n "$DEPENDENCIES" ]; then
          readarray -t dependencies <<< "$DEPENDENCIES"
        
          for dependency in "${dependencies[@]}"; do
            [[ -z "$dependency" ]] && continue

            OPTIONS+=('--dependency')
            OPTIONS+=("$dependency")
          done
        fi
        
        ThunderPipe create manifest "$NAME" "$VERSION" "${OPTIONS[@]}"
      env:
        NAME: ${{ inputs.name }}
        DESCRIPTION: ${{ inputs.description }}
        VERSION: ${{ inputs.version }}
        WEBSITE: ${{ inputs.website }}
        DEPENDENCIES: ${{ inputs.dependencies }}
        DIRECTORY: '${{ github.workspace }}/package/'

    - name: Validate Package
      shell: bash
      run: |
        ThunderPipe validate package "$PACKAGE_FOLDER" "$TEAM" \
          --token "$TOKEN" \
          --host "$HOST"
      env:
        PACKAGE_FOLDER: '${{ github.workspace }}/package/'
        TEAM: ${{ inputs.team }}
        TOKEN: ${{ inputs.token }}
        HOST: ${{ inputs.host }}

    ### ---
    ### Publish Package
    ### ---
    - name: Zip Package
      id: zip
      shell: bash
      run: |
        rm -f "$OUTPUT_FILE"
  
        (
          cd "$SOURCE_FOLDER"
          zip -r "$OUTPUT_FILE" .
        )
      env:
        SOURCE_FOLDER: '${{ github.workspace }}/package/'
        OUTPUT_FILE: '${{ github.workspace }}/${{ inputs.team }}-${{ inputs.name }}-${{ inputs.version }}.zip'

    - name: Publish Package
      shell: bash
      run: |
        OPTIONS=()

        if [ -n "$HOST" ]; then
          OPTIONS+=('--host')
          OPTIONS+=("$HOST")
        fi

        if [ "$HAS_NSFW" = 'true' ]; then
          OPTIONS+=('--has-nsfw')
        fi

        if [ -n "$CATEGORIES" ]; then
          readarray -t categories <<< "$CATEGORIES"
        
          for category in "${categories[@]}";
          do
            [ -z "$category" ] && continue
        
            OPTIONS+=('--category')
            OPTIONS+=("$category")
          done
        fi

        ThunderPipe publish "$FILE_PATH" "$TEAM" "$COMMUNITY" \
          --token "$TOKEN" \
          "${OPTIONS[@]}"
      env:
        FILE_PATH: '${{ github.workspace }}/${{ inputs.team }}-${{ inputs.name }}-${{ inputs.version }}.zip'
        TEAM: ${{ inputs.team }}
        COMMUNITY: ${{ inputs.community }}
        TOKEN: ${{ inputs.token }}
        HAS_NSFW: ${{ inputs.has-nsfw }}
        CATEGORIES: ${{ inputs.categories }}
        HOST: ${{ inputs.host }}
