name: 'Upload Package to Thunderstore'
description: 'Builds, validates, packages and publishes a Thunderstore pacakge'
author: 'WarperSan'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  community:
    description: 'Slug of the community to publish the package to'
    required: true
  team:
    description: 'Name of team publishing the package'
    required: true
  name:
    description: 'Name of the package'
    required: true
  description:
    description: 'Short description of the package'
    required: false
    default: ''
  version:
    description: 'Semantic version of the package'
    required: true
  website:
    description: 'URL of the package''s website'
    required: false
    default: ''
  has-nsfw:
    description: 'Marks the package as "Not Safe For Work" (NSFW)'
    required: false
    default: false
  token:
    description: 'Authentication token used by the service account'
    required: true

# outputs
# runs
